config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #

  root "articles#index"

  # get "/articles/:id", to: "articles#show"
  # get "/articles", to: "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create

    acceptedParams = article_params

    @article = Article.new(acceptedParams)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    acceptedParams = article_params

    if @article.update(acceptedParams)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    #render :index
    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>

<!--<a href="/articles/new">Create new</a>-->
<%= link_to "New Article", new_article_path %>
<table>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td>
<!--        <a href="<%#= article_path(article) %>" target="_blank">-->
<!--            View-->
<!--        </a>-->
        <%= link_to 'View', article %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Articles#new</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>

<%= link_to "Go Back", '/articles' %>
<br>

<label for="id">Id:</label>
<p><%= @article.id %></p>

<label for="id">Title:</label>
<p><%= @article.title %></p>

<label for="id">Body:</label>
<p><%= @article.body %></p>

<%= link_to "Edit", edit_article_path(@article) %>

<%= link_to "Delete", article_path(@article), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>